TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''
TWITTER_ACCESS_TOKEN = ''
TWITTER_TOKEN_SECRET = ''

FROM_ADDRESS = ''
TO_ADDRESS = ''

SMTP_SERVER = 'localhost'
SMTP_USERNAME = ''
SMTP_PASSWORD = ''

REDIS_SERVER='localhost'
REDIS_PORT=6379
REDIS_DB=1
